services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    expose:
      - "3010"
    networks:
      - app-network

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    expose:
      - "8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge